name: Postman mTLS REST API tests

on:
  push:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Podman and run Quarkus mTLS Auth project
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | podman login docker.io -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run Quarkus mTLS Auth project
        run: |
          podman pull docker.io/amusarra/quarkus-mtls-auth:latest
          podman run -d --name quarkus-mtls-auth -p 8443:8443 amusarra/quarkus-mtls-auth:latest

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run Postman Collection and Generate Report
        run: |
            postman collection run collections/quarkus-mtls-collection-with-test.json \
            --environment config/environments/local.json \
            --ssl-client-cert-list config/certificates/client-certificates.json \
            --ssl-extra-ca-certs certificates/ca/ca_cert.pem \
            --verbose \
            --reporters html,cli \
            --reporter-html-export postman_report.html

      - name: Upload Postman Report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: postman_report.html

      - name: Add summary with report link
        run: |
          echo "## Postman Test Report" >> $GITHUB_STEP_SUMMARY
          echo "Scarica il report HTML generato dai test di Postman:" >> $GITHUB_STEP_SUMMARY
          echo "[Download postman_report.html](./artifact/postman-report/postman_report.html)" >> $GITHUB_STEP_SUMMARY

      - name: Stop and remove Podman container
        if: always()
        run: |
          podman stop quarkus-mtls-auth
          podman rm quarkus-mtls-auth